using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace CharacterLogic.EditorTools
{
    /// <summary>
    /// Translates the Ukrainian hierarchy names generated by <see cref="ParkourMapTool"/> into
    /// consistent English names. Works both on freshly generated worlds (the tool itself now emits
    /// English names) and on scenes that were built before the translation, so no regeneration
    /// is required. Suffixes such as " Border L", " Tower Body" or " Post 0" are preserved.
    /// </summary>
    public static class ParkourNameLocalizer
    {
        private const string RootName = "Parkour World";

        private static readonly string[] UkrainianNames =
        {
            "Штаб-квартира Старт",
            "Розгін до краю",
            "Тераса після телепорту",
            "Тераса пентхауса",
            "Поверхівка Блок А",
            "Поверхівка Блок Б",
            "Верхній ярус кварталу",
            "Висотний скайбрідж",
            "Каньйон забігу по стінах",
            "Вертолітний майданчик Саміт",
            "Сталева балка над безоднею",
            "Оглядовий майданчик",
            "Спуск-трамплін Альфа",
            "Галерея швидкісного підкату",
            "Передфінішний спринт",
            "Фінішна площа",
            "Стрілки віраж у квартал",
            "Стрілки верхній ярус",
            "Стрілки фініш біг",
            "Стрілки розбіг",
            "Стрілки тераса",
            "Стрілки каньйон",
            "Стрілки до спуску",
            "Стрілки трамплін",
            "Стрілки підкат",
            "Стрілки блок А",
            "Стрілки блок Б",
            "Стрілки старт",
            "Стрілки міст",
            "Поручень старт",
            "Поручень міст",
            "Пілон ТП L",
            "Пілон ТП R",
            "Банер ТЕЛЕПОРТ",
            "Вольт HVAC",
            "Вольт спуск",
            "Стіна забігу L",
            "Стіна забігу R",
            "Геліпад коло",
            "Геліпад HBar",
            "Геліпад H1",
            "Геліпад H2",
            "Стартова лінія",
            "Стартова смуга біла",
            "Арка старт верх",
            "Арка старт L",
            "Арка старт R",
            "Фініш стрічка",
            "Фініш стіна",
            "Фініш банер",
            "Фініш верх",
            "Фініш L",
            "Фініш R",
            "Чекпоінт телепорт",
            "Чекпоінт квартал",
            "Чекпоінт тераса",
            "Чекпоінт стіни",
            "Чекпоінт саміт",
            "Чекпоінт підкат",
            "Чекпоінт фініш",
            "Чекпоінт старт",
            "Чекпоінт міст",
            "Місто близько",
            "Місто середнє",
            "Місто далеке",
            "Підкат",
            "Сонце"
        };

        private static readonly string[] EnglishNames =
        {
            "HQ Start",
            "Edge Sprint",
            "Post-Teleport Terrace",
            "Penthouse Terrace",
            "Rooftop Block A",
            "Rooftop Block B",
            "District Upper Tier",
            "High Skybridge",
            "Wall Run Canyon",
            "Summit Helipad",
            "Steel Beam Chasm",
            "Observation Deck",
            "Drop Ramp Alpha",
            "Speed Slide Gallery",
            "Pre-Finish Sprint",
            "Finish Plaza",
            "District Turn Chevrons",
            "Upper Tier Chevrons",
            "Finish Run Chevrons",
            "Sprint Chevrons",
            "Terrace Chevrons",
            "Canyon Chevrons",
            "Descent Chevrons",
            "Ramp Chevrons",
            "Slide Chevrons",
            "Block A Chevrons",
            "Block B Chevrons",
            "Start Chevrons",
            "Bridge Chevrons",
            "Start Railing",
            "Bridge Railing",
            "Teleport Pylon L",
            "Teleport Pylon R",
            "Teleport Banner",
            "HVAC Vault",
            "Descent Vault",
            "Wall Run L",
            "Wall Run R",
            "Helipad Circle",
            "Helipad HBar",
            "Helipad H1",
            "Helipad H2",
            "Start Line Red",
            "Start Line White",
            "Start Arch Top",
            "Start Arch Pylon L",
            "Start Arch Pylon R",
            "Finish Tape",
            "Finish Wall",
            "Finish Banner",
            "Finish Gate Top",
            "Finish Gate Pylon L",
            "Finish Gate Pylon R",
            "Checkpoint Teleport",
            "Checkpoint District",
            "Checkpoint Terrace",
            "Checkpoint WallRun",
            "Checkpoint Summit",
            "Checkpoint Slide",
            "Checkpoint Finish",
            "Checkpoint Start",
            "Checkpoint Bridge",
            "City Near",
            "City Mid",
            "City Far",
            "Slide Gate",
            "Sun"
        };

        [MenuItem("Tools/Parkour/4. Localize Names To English")]
        public static void LocalizeFromMenu()
        {
            int renamed = LocalizeActiveScene(true);
            Debug.Log("[ParkourNameLocalizer] Renamed " + renamed + " objects to English names.");
        }

        /// <summary>
        /// Renames every Ukrainian-named object in the active scene (the whole scene is scanned, so
        /// lights such as "Сонце" are covered as well). Returns the number of renamed objects.
        /// </summary>
        public static int LocalizeActiveScene(bool save)
        {
            Scene scene = SceneManager.GetActiveScene();
            int renamed = 0;

            foreach (GameObject rootObject in scene.GetRootGameObjects())
            {
                renamed += LocalizeHierarchy(rootObject.transform);
            }

            if (renamed > 0)
            {
                EditorSceneManager.MarkSceneDirty(scene);
                if (save)
                {
                    EditorSceneManager.SaveOpenScenes();
                }
            }

            return renamed;
        }

        public static int LocalizeHierarchy(Transform root)
        {
            if (root == null)
            {
                return 0;
            }

            int renamed = 0;
            Transform[] all = root.GetComponentsInChildren<Transform>(true);
            for (int i = 0; i < all.Length; i++)
            {
                Transform current = all[i];
                string translated = Translate(current.name);
                if (translated == current.name)
                {
                    continue;
                }

                current.name = translated;
                renamed++;
            }

            return renamed;
        }

        /// <summary>
        /// Replaces the longest matching Ukrainian prefix while keeping the English suffix intact,
        /// so "Штаб-квартира Старт Border L" becomes "HQ Start Border L".
        /// </summary>
        public static string Translate(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return value;
            }

            int bestIndex = -1;
            int bestLength = -1;
            for (int i = 0; i < UkrainianNames.Length; i++)
            {
                string candidate = UkrainianNames[i];
                if (candidate.Length <= bestLength)
                {
                    continue;
                }

                if (value.StartsWith(candidate, System.StringComparison.Ordinal))
                {
                    bestIndex = i;
                    bestLength = candidate.Length;
                }
            }

            if (bestIndex < 0)
            {
                return value;
            }

            return EnglishNames[bestIndex] + value.Substring(bestLength);
        }
    }
}
